version: "3"
services:
  openldap:
      build:
        context: .
        dockerfile: ./docker/Dockerfile-Openldap
      restart: always
      container_name: "OpenLDAP"
      env_file:
        - ./env/.env_ldap
      volumes:
          - 'openldap_data:/bitnami/openldap'
          - './config:/ldifs/custom'
      ports:
          - '389:1389'
          - '636:1636'
volumes:
  openldap_data: